export const backgroundColor = (theme) => {
  switch (theme) {
    case 'mytheme':
      return '#000914';
    case 'light':
      return '#bbbbbb';
    case 'dark':
      return '#1D232A';
    case 'cupcake':
      return '#b9b0b0';
    case 'bumblebee':
      return '#b1abab';
    case 'emerald':
      return '#bbbbbb';
    case 'corporate':
      return '#bbbbbb';
    case 'synthwave':
      return '#1A103C';
    case 'retro':
      return '#E4D8B4';
    case 'cyberpunk':
      return '#FFEE00';
    case 'valentine':
      return '#F0D6E8';
    case 'halloween':
      return '#212121';
    case 'garden':
      return '#b3adad';
    case 'forest':
      return '#171212';
    case 'aqua':
      return '#345CA8';
    case 'lofi':
      return '#bbbbbb';
    case 'pastel':
      return '#bbbbbb';
    case 'fantasy':
      return '#bbbbbb';
    case 'wireframe':
      return '#bbbbbb';
    case 'black':
      return '#000000';
    case 'luxury':
      return '#09090B';
    case 'dracula':
      return '#272935';
    case 'cmyk':
      return '#bbbbbb';
    case 'autumn':
      return '#C6C3C3';
    case 'business':
      return '#212121';
    case 'acid':
      return '#9b9292';
    case 'lemonade':
      return '#bbbbbb';
    case 'night':
      return '#0F1729';
    case 'coffee':
      return '#211720';
    case 'winter':
      return '#bbbbbb';
    default:
      return '#000914';
  }
};
